//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickyController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickyController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;backspace&quot;: 14, &quot;tab&quot;: 15, &quot;clear&quot;: 0, &quot;enter&quot;: 28, &quot;shift&quot;: 42, &quot;ctrl&quot;: 29, &quot;alt&quot;: 56, &quot;pause&quot;: 0, &quot;caps_lock&quot;: 58, &quot;esc&quot;: 1, &quot; &quot;: 57, &quot;page_up&quot;: 73, &quot;page_down&quot;: 81, &quot;end&quot;: 79, &quot;home&quot;: 71, &quot;left_arrow&quot;: 75, &quot;up_arrow&quot;: 72, &quot;right_arrow&quot;: 77, &quot;down_arrow&quot;: 80, &quot;select&quot;: 0, &quot;print&quot;: 0, &quot;execute&quot;: 0, &quot;print_screen&quot;: 84, &quot;ins&quot;: 82, &quot;del&quot;: 83, &quot;help&quot;: 99, &quot;0&quot;: 11, &quot;1&quot;: 2, &quot;2&quot;: 3, &quot;3&quot;: 4, &quot;4&quot;: 5, &quot;5&quot;: 6, &quot;6&quot;: 7, &quot;7&quot;: 8, &quot;8&quot;: 9, &quot;9&quot;: 10, &quot;a&quot;: 30, &quot;b&quot;: 48, &quot;c&quot;: 46, &quot;d&quot;: 32, &quot;e&quot;: 18, &quot;f&quot;: 33, &quot;g&quot;: 34, &quot;h&quot;: 35, &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ScanCodes {
            get {
                return ResourceManager.GetString("ScanCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;backspace&quot;: 8, &quot;tab&quot;: 9, &quot;clear&quot;: 254, &quot;enter&quot;: 13, &quot;shift&quot;: 16, &quot;ctrl&quot;: 17, &quot;alt&quot;: 18, &quot;pause&quot;: 19, &quot;caps_lock&quot;: 20, &quot;esc&quot;: 27, &quot; &quot;: 32, &quot;page_up&quot;: 33, &quot;page_down&quot;: 34, &quot;end&quot;: 35, &quot;home&quot;: 36, &quot;left_arrow&quot;: 37, &quot;up_arrow&quot;: 38, &quot;right_arrow&quot;: 39, &quot;down_arrow&quot;: 40, &quot;select&quot;: 41, &quot;print&quot;: 42, &quot;execute&quot;: 43, &quot;print_screen&quot;: 44, &quot;ins&quot;: 45, &quot;del&quot;: 46, &quot;help&quot;: 47, &quot;0&quot;: 48, &quot;1&quot;: 49, &quot;2&quot;: 50, &quot;3&quot;: 51, &quot;4&quot;: 52, &quot;5&quot;: 53, &quot;6&quot;: 54, &quot;7&quot;: 55, &quot;8&quot;: 56, &quot;9&quot;: 57, &quot;a&quot;: 65, &quot;b&quot;: 66, &quot;c&quot;: 67, &quot;d&quot;: 68, &quot;e&quot;: 69, &quot;f&quot;: 70, &quot;g&quot;: 7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VirtualKeyCodes {
            get {
                return ResourceManager.GetString("VirtualKeyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;)&quot;: &quot;0&quot;, &quot;!&quot;: &quot;1&quot;, &quot;\&quot;&quot;: &quot;&apos;&quot;, &quot;£&quot;: &quot;3&quot;, &quot;$&quot;: &quot;4&quot;, &quot;%&quot;: &quot;5&quot;, &quot;^&quot;: &quot;6&quot;, &quot;&amp;&quot;: &quot;7&quot;, &quot;*&quot;: &quot;8&quot;, &quot;(&quot;: &quot;9&quot;, &quot;:&quot;: &quot;;&quot;, &quot;+&quot;: &quot;=&quot;, &quot;&lt;&quot;: &quot;,&quot;, &quot;_&quot;: &quot;-&quot;, &quot;&gt;&quot;: &quot;.&quot;, &quot;?&quot;: &quot;/&quot;, &quot;@&quot;: &quot;&apos;&quot;, &quot;{&quot;: &quot;[&quot;, &quot;|&quot;: &quot;\\&quot;, &quot;}&quot;: &quot;]&quot;, &quot;~&quot;: &quot;#&quot;}.
        /// </summary>
        public static string VirtualKeyCodesShift {
            get {
                return ResourceManager.GetString("VirtualKeyCodesShift", resourceCulture);
            }
        }
    }
}
