//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickyController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickyController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BACKSPACE&quot;:14,&quot;TAB&quot;:15,&quot;CLEAR&quot;:76,&quot;ENTER&quot;:28,&quot;SHIFT&quot;:42,&quot;CTRL&quot;:29,&quot;ALT&quot;:56,&quot;PAUSE&quot;:0,&quot;CAPS_LOCK&quot;:58,&quot;ESC&quot;:1,&quot; &quot;:57,&quot;PAGE_UP&quot;:73,&quot;PAGE_DOWN&quot;:81,&quot;END&quot;:79,&quot;HOME&quot;:71,&quot;LEFT_ARROW&quot;:75,&quot;UP_ARROW&quot;:72,&quot;RIGHT_ARROW&quot;:77,&quot;DOWN_ARROW&quot;:80,&quot;SELECT&quot;:0,&quot;PRINT&quot;:0,&quot;EXECUTE&quot;:0,&quot;PRINT_SCREEN&quot;:84,&quot;INS&quot;:82,&quot;DEL&quot;:83,&quot;HELP&quot;:99,&quot;0&quot;:11,&quot;1&quot;:2,&quot;2&quot;:3,&quot;3&quot;:4,&quot;4&quot;:5,&quot;5&quot;:6,&quot;6&quot;:7,&quot;7&quot;:8,&quot;8&quot;:9,&quot;9&quot;:10,&quot;a&quot;:30,&quot;b&quot;:48,&quot;c&quot;:46,&quot;d&quot;:32,&quot;e&quot;:18,&quot;f&quot;:33,&quot;g&quot;:34,&quot;h&quot;:35,&quot;i&quot;:23,&quot;j&quot;:36,&quot;k&quot;:37,&quot;l&quot;:38,&quot;m&quot;:50,&quot;n&quot;:49,&quot;o&quot;:24,&quot;p&quot;:25,&quot;q&quot;:16,&quo....
        /// </summary>
        public static string ScanCodes {
            get {
                return ResourceManager.GetString("ScanCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;BACKSPACE&quot;: 8, &quot;TAB&quot;: 9, &quot;CLEAR&quot;: 12, &quot;ENTER&quot;: 13, &quot;SHIFT&quot;: 16, &quot;CTRL&quot;: 17, &quot;ALT&quot;: 18, &quot;PAUSE&quot;: 19, &quot;CAPS_LOCK&quot;: 20, &quot;ESC&quot;: 27, &quot; &quot;: 32, &quot;PAGE_UP&quot;: 33, &quot;PAGE_DOWN&quot;: 34, &quot;END&quot;: 35, &quot;HOME&quot;: 36, &quot;LEFT_ARROW&quot;: 37, &quot;UP_ARROW&quot;: 38, &quot;RIGHT_ARROW&quot;: 39, &quot;DOWN_ARROW&quot;: 40, &quot;SELECT&quot;: 41, &quot;PRINT&quot;: 42, &quot;EXECUTE&quot;: 43, &quot;PRINT_SCREEN&quot;: 44, &quot;INS&quot;: 45, &quot;DEL&quot;: 46, &quot;HELP&quot;: 47, &quot;0&quot;: 48, &quot;1&quot;: 49, &quot;2&quot;: 50, &quot;3&quot;: 51, &quot;4&quot;: 52, &quot;5&quot;: 53, &quot;6&quot;: 54, &quot;7&quot;: 55, &quot;8&quot;: 56, &quot;9&quot;: 57, &quot;a&quot;: 65, &quot;b&quot;: 66, &quot;c&quot;: 67, &quot;d&quot;: 68, &quot;e&quot;: 69, &quot;f&quot;: 70, &quot;g&quot;: 71 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VirtualKeyCodes {
            get {
                return ResourceManager.GetString("VirtualKeyCodes", resourceCulture);
            }
        }
    }
}
