//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickyControllerGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickyControllerGUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;displayname&quot; : 
        ///    {
        ///        &quot;LeftClick&quot;:  &quot;Left Click&quot;,
        ///        &quot;LeftDown&quot; : &quot;Left Down&quot;,
        ///        &quot;LeftUp&quot; : &quot;Left Up&quot;,
        ///        &quot;RightClick&quot;: &quot;Right Click&quot;,
        ///        &quot;RightDown&quot; : &quot;Right Down&quot;,
        ///        &quot;RightUp&quot; : &quot;Right Up&quot;,
        ///        &quot;MiddleClick&quot;: &quot;Middle Click&quot;,
        ///        &quot;MiddleDown&quot; : &quot;Middle Down&quot;,
        ///        &quot;MiddleUp&quot; : &quot;Middle Up&quot;,
        ///        &quot;Wait&quot;: &quot;Wait&quot;,
        ///        &quot;EnterText&quot; : &quot;Enter Text&quot;,
        ///        &quot;PressKey&quot; : &quot;Press Key&quot;,
        ///        &quot;KeyDown&quot; : &quot;Key Down&quot;,
        ///        &quot;KeyUp&quot; : &quot;Key Up&quot;
        ///    }, 
        ///    &quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodToListDisplayName {
            get {
                return ResourceManager.GetString("MethodToListDisplayName", resourceCulture);
            }
        }
    }
}
