//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickyControllerGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickyControllerGUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;Mouse Click&quot;:&quot;mc&quot;,
        ///&quot;Move Mouse&quot;: &quot;mv&quot;,
        ///&quot;Scroll Wheel&quot;: &quot;sw&quot;,
        ///&quot;Enter Text&quot; : &quot;et&quot;,
        ///&quot;Press Key&quot; : &quot;kp&quot;,
        ///&quot;Key Down&quot; : &quot;kd&quot;,
        ///&quot;Key Up&quot; : &quot;kr&quot;,
        ///&quot;Wait&quot; : &quot;wt&quot;
        ///}.
        /// </summary>
        internal static string CommandsToListDisplayName {
            get {
                return ResourceManager.GetString("CommandsToListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mc&quot;: [&quot;MouseViewModel&quot;, &quot;MouseClick&quot;],
        ///	&quot;mv&quot;: [&quot;MouseViewModel&quot;, &quot;MoveMouse&quot;],
        ///	&quot;sw&quot;: [&quot;MouseViewModel&quot;, &quot;ScrollWheel&quot;],
        ///	&quot;et&quot; : [&quot;KeyboardViewModel&quot;, &quot;EnterText&quot;],
        ///	&quot;kp&quot; : [&quot;KeyboardViewModel&quot;, &quot;KeyPress&quot;],
        ///	&quot;kr&quot; : [&quot;KeyboardViewModel&quot;, &quot;KeyRelease&quot;],
        ///	&quot;kd&quot; : [&quot;KeyboardViewModel&quot;, &quot;KeyDown&quot;],
        ///	&quot;wt&quot; : [&quot;UtilityViewModel&quot;, &quot;Wait&quot;]
        ///}.
        /// </summary>
        internal static string CommandsToMethods {
            get {
                return ResourceManager.GetString("CommandsToMethods", resourceCulture);
            }
        }
    }
}
